### ISSUE TITLE
add build/install info

### ISSUE THREAD

**Issue by jwaldmann** [jgotoh/distributed-frp-dunai#1]
* requires `SDL2_gfx-devel` (cabal-install will warn about that)
* ghc version? (seems to work with 8.4.4)

`cabal test --allow-newer`:

with ghc-8.8: 
```
src/Control/Distributed/Process/Internal/Primitives.hs:1273:17: error:
    • Could not deduce (MonadFail Process) arising from a use of ‘fail’
```
with ghc-8.6: 
```
tests/ServerTest.hs:87:5: error:
    • No instance for (Control.Monad.Fail.MonadFail P.Process)
```

**Comment by jgotoh** [comment]
I added some instructions related to building and installing the project in a new branch, see [1].

I created a fork of distributed-process (just a small change) which lets us use Cloud Haskell and newer GHC Versions. I tested it with 8.8.3 and 8.2.2.
Does it work for you in the new branch?

[1] https://github.com/jgotoh/distributed-frp-dunai/tree/1_install_info

**Comment by jwaldmann** [comment]
yes, that works.Thanks! I tested with ghc-8.8.3. I do need `--allow-newer`. Else,
```
cabal install
...
[__5] rejecting: distributed-process-extras-0.3.5 (conflict:
hashable==1.3.0.0, distributed-process-extras => hashable>=1.2.0.5 && <1.3)
```

**Comment by jgotoh** [comment]
> And `cabal test --allow-newer` also works with ghc-8.10.1

Thanks, good to know. Somehow I can't install ghc 8.10 on my machine.

I added a note to the README regarding `--allow-newer`.
